apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.15.0
    helm:
      releaseName: vault
      values: |
        injector:
          enabled: false

        server:
          dev:
            enabled: true

          postStart:
            - /bin/sh
            - -c

            - |
              sleep 10s &&\

              printf 'path "secret/*"{\ncapabilities=["read"]\n}' | vault policy write argo - &&\
              vault auth enable kubernetes &&\
              vault write auth/kubernetes/config\
                kubernetes_host='https://$KUBERNETES_PORT_443_TCP_ADDR:443' \
                disable_iss_validation=true &&\
                kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt\

              vault write auth/kubernetes/role/argocd \
                bound_service_account_names=argocd-server \
                bound_service_account_namespaces=argocd \
                policies="argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
